apiVersion: v1
kind: Namespace
metadata:
    name: ns-witest
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: ksa-witest
  namespace: ns-witest
  annotations:
    iam.gke.io/gcp-service-account: "gsa-witest@myproj-193510.iam.gserviceaccount.com"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-witest
  namespace: ns-witest
spec:
  serviceAccountName: ksa-witest
  containers:
    - name: auth-container
      image: google/cloud-sdk
      stdin: true 
      tty: true
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: iam.gke.io/gke-metadata-server-enabled
              operator: In
              values:
              - "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-witest-2
  namespace: ns-witest
spec:
  serviceAccountName: ksa-witest
  containers:
    - name: auth-container
      image: google/cloud-sdk
      stdin: true 
      tty: true
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: iam.gke.io/gke-metadata-server-enabled
              operator: NotIn
              values:
              - "true"